[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
board_build.partitions = default_16MB.csv
lib_deps =
    m5stack/M5Unified @ 0.2.7
    meganetaaan/M5Stack-Avatar @ ^0.10.0
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git
monitor_speed = 921600
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DENABLE_CAMERA
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
